In [8]:
import os
import json
import numpy as np

def print_inputs_outputs_only(directory_path, problem_name):
    # Full path to the JSON file
    file_path = os.path.join(directory_path, f"{problem_name}.json")

    if not os.path.isfile(file_path):
        print(f"File not found: {file_path}")
        return

    # Load the JSON content
    with open(file_path, 'r') as f:
        data = json.load(f)

    print(f"Problem Name: {problem_name}\n")

    # Print all inputs and outputs from train
    for sample in data.get("train", []):
        print(f"Input:\n{np.array(sample['input'])}\n")
        print(f"Output:\n{np.array(sample['output'])}\n")

    # Print all inputs and outputs from test
    for sample in data.get("test", []):
        print(f"Input:\n{np.array(sample['input'])}\n")
        print(f"Output:\n{np.array(sample['output'])}\n")

# === USAGE ===
directory = "/teamspace/studios/this_studio/data/training"
problem_name = "10fcaaa3"

print_inputs_outputs_only(directory, problem_name)


Problem Name: 10fcaaa3

Input:
[[0 0 0 0]
 [0 5 0 0]]

Output:
[[8 0 8 0 8 0 8 0]
 [0 5 0 0 0 5 0 0]
 [8 0 8 0 8 0 8 0]
 [0 5 0 0 0 5 0 0]]

Input:
[[0 0 6 0]
 [0 0 0 0]
 [0 6 0 0]]

Output:
[[0 0 6 0 0 0 6 0]
 [8 8 8 8 8 8 8 8]
 [0 6 0 8 0 6 0 8]
 [8 0 6 0 8 0 6 0]
 [8 8 8 8 8 8 8 8]
 [0 6 0 0 0 6 0 0]]

Input:
[[0 0 0]
 [0 4 0]
 [0 0 0]
 [0 0 0]
 [4 0 0]]

Output:
[[8 0 8 8 0 8]
 [0 4 0 0 4 0]
 [8 0 8 8 0 8]
 [0 8 8 0 8 0]
 [4 0 0 4 0 0]
 [8 8 8 8 8 8]
 [0 4 0 0 4 0]
 [8 0 8 8 0 8]
 [0 8 8 0 8 0]
 [4 0 0 4 0 0]]

Input:
[[0 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Output:
[[8 0 8 0 8 0 8 0]
 [0 2 0 0 0 2 0 0]
 [8 0 8 0 8 0 8 0]
 [0 0 0 0 0 0 0 0]
 [8 0 8 0 8 0 8 0]
 [0 2 0 0 0 2 0 0]
 [8 0 8 0 8 0 8 0]
 [0 0 0 0 0 0 0 0]]

Input:
[[0 3 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 3 0]
 [0 0 0 0 0]
 [0 3 0 0 0]]

Output:
[[0 3 0 0 0 0 3 0 0 0]
 [8 0 8 0 0 8 0 8 0 0]
 [0 0 8 0 8 0 0 8 0 8]
 [0 0 0 3 0 0 0 0 3 0]
 [8 0 8 0 8 8 0 8 0 8]
 [8 3 8 0 0 8 3 8 0 0]
 [8 3 8 0 0 8 3 8 0 0]
 [8 0 8 

In [2]:
! unzip /teamspace/studios/this_studio/sully_training.zip

Archive:  /teamspace/studios/this_studio/sully_training.zip
   creating: sully_training/
  inflating: sully_training/007bbfb7.json  
  inflating: sully_training/025d127b.json  
  inflating: sully_training/0520fde7.json  
  inflating: sully_training/05269061.json  
  inflating: sully_training/06df4c85.json  
  inflating: sully_training/08ed6ac7.json  
  inflating: sully_training/0962bcdd.json  
  inflating: sully_training/0a938d79.json  
  inflating: sully_training/0b148d64.json  
  inflating: sully_training/0ca9ddb6.json  
  inflating: sully_training/18419cfa.json  
  inflating: sully_training/195ba7dc.json  
  inflating: sully_training/19bb5feb.json  
  inflating: sully_training/1cf80156.json  
  inflating: sully_training/1f85a75f.json  
  inflating: sully_training/2013d3e2.json  
  inflating: sully_training/22168020.json  
  inflating: sully_training/22eb0ac0.json  
  inflating: sully_training/23b5c85d.json  
  inflating: sully_training/25d487eb.json  
  inflating: sully_training/25f

In [3]:
import zipfile
import os

# Path to your zip file
zip_path = '/teamspace/studios/this_studio/ARC-AGI-2-main (1).zip'

# Destination folder (same directory, folder name without .zip)
extract_to = zip_path.replace('.zip', '').replace(' (1)', '')  # Optional: rename for clean folder

# Make sure the directory exists
os.makedirs(extract_to, exist_ok=True)

# Unzip the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print(f"Extraction complete. Files are in: {extract_to}")


Extraction complete. Files are in: /teamspace/studios/this_studio/ARC-AGI-2-main
